import type { Metadata } from 'next';
import { ABeeZee, Cantarell } from 'next/font/google';
import '../globals.css';

const abeezee = ABeeZee({
  variable: '--font-abeezee',
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal', 'italic'],
});

const cantarell = Cantarell({
  variable: '--font-cantarell',
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Gabriel Verdan - Dev Fullstack',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="pt-BR"
      className={`${abeezee.variable} ${cantarell.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <main className="m-auto min-h-screen w-full lg:min-w-3/4">
          {children}
        </main>
      </body>
    </html>
  );
}
